version: "2"
run:
  build-tags:
    - integration
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - maintidx
    - misspell
    - nilnil
    - prealloc
    - predeclared
    - revive
    - thelper
    - tparallel
    - wrapcheck
  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*os.File).Close
        - os.Setenv
        - os.Remove
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - unlambda
    gocyclo:
      min-complexity: 15
    godot:
      scope: declarations
      capital: true
    gosec:
      excludes:
        - G306
        - G104
        - G204
        - G304
      severity: low
      confidence: low
    maintidx:
      under: 20
    nilnil:
      checked-types:
        - ptr
        - func
        - iface
        - map
        - chan
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
      ignore-package-globs:
        - github.com/caner-cetin/halycon/internal/*
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - gocognit
          - goconst
          - gosec
        path: _test\.go
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - revive
        text: 'package-comments:'
    paths:
      - third_party$
      - builtin$
      - examples$
    presets:
      - comments
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
