name: databases-redis
services:
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: dragonfly --requirepass ${REDIS_PASSWORD}
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
    networks:
      - database_bridge

networks:
  database_bridge:
    external: true

volumes:
  dragonflydata:
