services:
    backend:
        container_name: code-cansu-dev-backend
        build:
            context: ../../code/backend/
            dockerfile: ./Dockerfile
        networks:
            - plane-dev
            - database_bridge
            - loki
        environment:
            - HF_TOKEN=${HF_TOKEN}
            - HF_MODEL_URL=${HF_MODEL_URL}
            - REDIS_URL=redis://databases-redis-dragonfly-1:6379/2
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - DATABASE_URL=${POSTGRESQL_URL}
            - LOKI_URL=http://loki:3169/loki/api/v1/push
        ports:
            - ${PORT:-6767}:${PORT:-6767}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
            - /run/systemd/private:/run/systemd/private
            - /tmp:/tmp
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_ADMIN
            - DAC_OVERRIDE
            - SYS_RESOURCE

        cgroup: host
        pid: host
        command: /app

networks:
    plane-dev:
        external: true
    database_bridge:
        external: true
    loki:
        external: true
