
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "perk/ubuntu-2204-arm64"
  config.vm.box_version = "20230712"
  config.vm.hostname = "testserver"
  config.vm.network "forwarded_port", id: 'ssh', guest: 22, host: 50022, host_ip: "127.0.0.1", auto_correct: false
  config.vm.network "forwarded_port", id: 'http', guest: 80, host: 4080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", id: 'https', guest: 443, host: 4483, host_ip: "127.0.0.1"
end
