# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: "cansu.dev"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "cansu.dev-observer-alertmanager:9093"

# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["cansu.dev-observer-prometheus:9090"]
  - job_name: "cadvisor"
    scrape_interval: 15s
    static_configs:
      - targets: ["cansu.dev-observer-cadvisor:8080"]
  - job_name: "node-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["cansu.dev-observer-node_exporter:9100"]
